const tintColorLight = '#fff';
const tintColorDark = '#fff';

export default {
  light: {
    primary: '#1682C2',
    text: '#000',
    background: '#f5f5f5',
    touchableOpacity: '#1377B0',
    tint: tintColorLight,
    tabIconDefault: '#fff',
    tabIconSelected: tintColorLight,
    tabSelectedBackground: '#2A5066',
    bottomNavigatorBackground: '#1682C2',
    labelLeitura: '#0067A4',
    tabBarPressColor: '#1377B0',
    textError: '#f00',
    inactiveTintColor: '#212121',
    activeTintColor: '#1682C2',
    buttonDefault: '#1377B0',
    defaultButtonLabel: '#fff',
    badgeBackground: '#2A5066',
    badgeText: '#fff',
  },
  dark: {
    primary: '#1662ff',
    text: '#ccc',
    background: '#181a1b',
    touchableOpacity: '#2B5269',
    tint: tintColorDark,
    tabIconDefault: '#fff',
    tabIconSelected: tintColorDark,
    tabSelectedBackground: '#2A5066',
    bottomNavigatorBackground: '#1682C2',
    labelLeitura: '#092738',
    tabBarPressColor: '#1662ff',
    textError: '#f00',
    inactiveTintColor: 'gray',
    activeTintColor: '#1662ff',
    buttonDefault: '#1377B0',
    defaultButtonLabel: '#fff',
    badgeBackground: '#2A5066',
    badgeText: '#fff',
  },
};
